# Generated by Django 4.2.22 on 2025-06-08 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_remove_recipe_ingredients_ingredientrecipe_recipe'),
        ('users', '0003_alter_user_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='cart',
            field=models.ManyToManyField(blank=True, related_name='user_cart', to='recipes.recipe', verbose_name='Корзина'),
        ),
        migrations.AddField(
            model_name='user',
            name='favourites',
            field=models.ManyToManyField(blank=True, related_name='favourites', to='recipes.recipe', verbose_name='Избранное'),
        ),
    ]
